SublimeText/sublime_lib

.flake8
This should get us started. I don't have a strong opinion about other rules.
=> Added .flake8 config.

st3/sublime_lib/__init__.py, st3/sublime_lib/view_buffer.py
This is a minimal implementation of the idea, plus a possibly-useful convenience method.
=> Added ViewBuffer class.

LICENSE
I assume we'll want to use the MIT license.
=> MIT License.

st3/sublime_lib/syntax.py, tests/test_syntax.py
Add some rudimentary YAML value parsing and a couple more tests.
=> Syntax utilities improvements

st3/sublime_lib/__init__.py, st3/sublime_lib/fancy_settings.py, tests/test_named_fancy_settings.py, unittesting.json
As #15, but implemented in a new class.
=> Added NamedFancySettings.

st3/sublime_lib/collection_utils.py, st3/sublime_lib/fancy_settings.py, st3/sublime_lib/syntax.py, tests/test_fancy_settings.py
Also modified the implementation of `projection`: now, only the `keys` argument must be iterable.
=> Factored out projection method. Added setting subscription tests.

.coveragerc
Provide more accurate coverage information.
=> Add coveragerc.

st3/sublime_lib/__init__.py, st3/sublime_lib/show_selection_panel.py, tests/test_selection_panel.py
For #31.
I think the function is fine, or close to it. The tests, on the other hand, are a bit gnarly.
=> Added show_selection_panel.

st3/sublime_lib/show_selection_panel.py, tests/test_selection_panel.py
Really dumb bug I didn't catch because the mock didn't complain.
=> Fixed types of flags and selected_index args.

tests/test_window_utils.py
Not sure about Linux; some distros or configurations might have the same problem.
=> Disabled menu visibility test on Mac.

st3/sublime_lib/syntax.py
Not sure why flake8 started complaining about this now.
=> Fixed flake error in syntax.

docs/source/extensions/prettify_special_methods.py
I'll want to do more hacking on the Sphinx output at some point, but this should be an improvement.
=> Improved prettification of special method docs.

st3/sublime_lib/flags.py, st3/sublime_lib/output_panel.py, st3/sublime_lib/settings_dict.py, st3/sublime_lib/show_selection_panel.py, st3/sublime_lib/view_stream.py, st3/sublime_lib/view_utils.py, st3/sublime_lib/window_utils.py
Improved doc content, formatting, line breaks, and more.
Added [`versionadded`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded) and [`versionchanged`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionchanged) directives as appropriate.
=> Improved docs in more files.

docs/source/index.rst
=> Added a note about API readiness.

docs/source/index.rst, st3/sublime_lib/__init__.py, st3/sublime_lib/_util/named_value.py, st3/sublime_lib/flags.py, st3/sublime_lib/settings_dict.py, st3/sublime_lib/show_selection_panel.py, st3/sublime_lib/view_utils.py, st3/sublime_lib/window_utils.py, tests/test_named_value.py
- Added missing `versionadded` and `versionchanged` directives.
- Added `LineEnding` enum to docs.
- Fixed a typo in `NamedSettingsDict`.
=> Last-minute docs fixes.

.gitignore, mypy.ini, stubs/sublime.pyi
A few things I ran into when writing annotations.
=> Minor fixes for mypy.

st3/sublime_lib/resource_path.py
Simpler than adding annotations.
=> Fix mypy complaints.

st3/sublime_lib/encodings.py, st3/sublime_lib/panel.py, st3/sublime_lib/resource_path.py, st3/sublime_lib/show_selection_panel.py
Also, ResourcePath didn't have a `.. versionadded:: 1.2`.
=> Added version notes for new features.

st3/sublime_lib/__init__.py, st3/sublime_lib/_util/locked_state.py, st3/sublime_lib/activity_indicator.py, tests/test_activity_indicator.py
For #114. I went with the name `ActivityIndicator`, which seems appropriately nonspecific.
Still needs docs and possibly more tests, but the implementation should be sound.
=> Add activity indicator.

docs/source/index.rst, st3/sublime_lib/activity_indicator.py, st3/sublime_lib/flags.py
Added docs for `ActivityIndicator`. Added `versionadded` to various docs.
=> Added docs for 1.4.

st3/sublime_lib/encodings.py, tests/test_encodings.py
=> Add Central European (Mac) encoding.

docs/source/conf.py, docs/source/extensions/better_toctree.py, docs/source/extensions/strip_annotations.py, docs/source/mocks/sublime.py
Fix various deprecation warnings. Should not change the output.
=> Update for Sphinx 4

st3/sublime_lib/activity_indicator.py
Use a weak reference so that `sublime.set_timeout` won't keep the reference alive. This will naturally stop the timeouts. Also manually clear the target upon deletion.
This is technically a change in behavior, but I think it makes sense as a bug fix.
=> Stop ActivityIndicator when the object reference is lost.
