st3/sublime_lib/__init__.py, st3/sublime_lib/output_panel.py, st3/sublime_lib/view_stream.py, tests/test_output_panel.py, tests/test_view_stream.py
Discussed briefly in #3.
Notes:
- `write` and `flush` constitute the informal stream interface. `flush` is, of course, a no-op. (I don't think there's any reason to do any buffering here.)
- `print` is a convenience method: `stream.print(foo)` rather than `print(foo, file=stream)`. It might be appropriate to throw a `TypeError` if the user passes a `file` argument.
- The behavior of `seek_start` is used in the `finish` method of the existing `OutputPanel` implementation. Because it is purely a view operation, I thought it made sense to implement at this lower level. `seek_end` and `seek` make sense in combination with `seek_start`.
- `clear` uses two commands, which could cause flickering in some extreme cases. However, the only workaround is creating a new command, which would require a …
=> Added ViewStream and OutputPanel.

st3/sublime_lib/__init__.py, st3/sublime_lib/fancy_settings.py, tests/test_fancy_settings.py
For #2.
The name could be changed. I'd be a bit leery of simply calling it “Settings”.
The `subscribe` method takes a “selector”, which maps the current state of a `FancySettings` to some value. (If `selector` is a string, it is interpreted as the name of a top-level setting.) When the `Settings` changes, if and only if the selected value changes, the given callback will be invoked with the new and old value as arguments. This is what I'd need for JS Custom, and I think it should handle most use cases.
Default values are not handled in this PR, though they should be easily compatible with this implementation.
The built-in `Settings` class supplies `None` for a nonexistent key instead of raising a `KeyError`. Should we follow suit or be stricter? Myself, I'd generally lean toward stricter, …
=> Added "fancy settings" with bracket access and better subscription.

st3/sublime_lib/view_stream.py, tests/test_view_stream.py
- ViewStream now extends [io.TextIOBase](https://docs.python.org/3/library/io.html#io.TextIOBase).
- `_check_selection` will raise if the selection is nonempty, because this could produce surprising behavior with `write` and `tell`.
- `seek` is refactored to avoid redundant checks.
- New `tell` method gives the position of the cursor.
- `read`, `readline`, and `detach` exist and raise `io.UnsupportedOperation`. We could implement `read` and `readline` if we want to.
- Documentation and tests.
=> ViewStream implements TextIOBase

st3/sublime_lib/output_panel.py, st3/sublime_lib/view_stream.py, tests/test_output_panel.py, tests/test_view_stream.py
You can pass a dictionary of settings to `__init__` to set them in the panel's view.
In addition to handling syntaxes and such, I'm hoping that this will suffice in place of more specific methods to handle error regexps.
=> Added settings argument to OutputPanel.

st3/sublime_lib/output_panel.py, st3/sublime_lib/view_stream.py, tests/test_view_stream.py
Had this idea while reviewing whatever PR it was that added the checks. Initially I had each check as a generator, but then I realized I'd end up wrapping a method up to 3 times and that didn't seem right, so I rewrote the guards into normal checks (that raise exceptions) and added a "meta" guard that these checks are passed to. Also added context manager support to unset the read-only flag.
I guess this PR is quite controversial, so let me know what you think.
Advantages:
- Communicates more clearly what state invariants are required for a method to run successfully.
- Gets rid of internal functions that were wrapped with `_wrap_read_only`.
Disadvantages:
- Higher complexity and less obvious for developers not used to decorators.
=> Use decorators to ensure valid ViewStream state

st3/sublime_lib/view_stream.py, tests/test_view_stream.py
The size returned from `write` is now measured, because it can be different than the length of the string argument.
In addition, the inserted text will not be auto-indented. This could conceivably be an option (like `force_write`).
=> Fixed bugs in ViewStream.write.

st3/sublime_lib/encodings.py, st3/sublime_lib/output_panel.py, st3/sublime_lib/view_utils.py, tests/test_view_utils.py
`sublime_lib.view_utils.new_view` is a useful shorthand way to create a new view. You can specify view name, syntax, settings, read-only, and more. The implementation is in `set_view_options`, which is also used in `OutputPanel`.
Is there reason to expose more options in `OutputPanel`? Are the missing options useful? I seem to recall that calling `assign_syntax` on an output panel causes weird things to happen, and the `name` and `scratch` options don't seem relevant.
=> Added view_utils.

st3/sublime_lib/output_panel.py, tests/test_output_panel.py
Continuing the discussion from #28.
This is a minimal-ish approach; I haven't created a `find` method.
Upon consideration, the constructor *doesn't* need to take the window and name -- not quite. We could instead give it the *view* and name, and it can get the window from there. This would be as similar as possible to the parent, which only takes a view, and it would save the call to `find_output_panel`. In this scenario, it would definitely make sense to provide a static `find` method taking a window argument.
Is there a sensible way to get the panel name from a view? The only way I can think of is to call `find_output_panel` for each name in `window.panels()`, which seems clumsy. On the other hand, it would be easy to verify a given (view, name) pair by checking that …
=> Split output panel creation behavior into constructor and `create`.

st3/sublime_lib/__init__.py, st3/sublime_lib/fancy_settings.py, tests/test_fancy_settings.py
This implementation is inspired by `defaultdict`, and I think it might be more consistent with existing practice.
When you index a `FancySettings` with a nonexistent key, it will call `self.__missing__(key)`  and return the result. The base implementation simply raises KeyError. A new `DefaultFancySettings` subclass takes a `defaults` parameter in its constructor and overrides `__missing__` to set and return a default value. This is basically how `defaultdict` works (although that class takes a `default_factory` function, not a `defaults` dict).
The major difference is that `NamedFancySettings` doesn't accept manual defaults, but the preferred way to supply defaults to a named settings object is to provide a default settings file. View-specific settings and other "anonymous" settings …
=> Implemented default settings logic in new DefaultFancySettings class.

st3/sublime_lib/__init__.py, st3/sublime_lib/settings_dict.py, tests/test_named_settings_dict.py, tests/test_settings_dict.py
Since we ended up basically implementing the `dict` interface, `SettingsDict` might be a more descriptive name than `FancySettings`. Looking for feedback.
=> Renamed FancySettings to SettingsDict.

st3/sublime_lib/enum.py, st3/sublime_lib/flags.py
Because there's already a dependency for this, there's no need to expose it here. Instead, we use the vendored version directly in `flags.py`.
=> Do not expose vendored enum library.

st3/sublime_lib/__init__.py, st3/sublime_lib/settings_dict.py, tests/test_settings_dict.py
`collections.ChainMap` can be used instead of `DefaultSettingsDict`, so the latter is unnecessary.
`SettingsDict` now implements `__iter__`, raising [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError). Formerly, calling `iter` on a `SettingsDict` would indirectly raise `TypeError`, which was confusing.
In principle, `NotImplementedError` is supposed to be used for methods that are supposed to be implemented in the future. The degree to which this describes `SettingDict.__iter__` depends on one's optimism that the Sublime API will someday permit this. Either way, I think that `NotImplementedError` is the clearest way to indicate that, unusually for a collection, `SettingsDict` is not iterable.
I've added tests checking the `NotImplementedError` …
=> Remove DefaultSettingsDict

docs/source/conf.py, docs/source/index.rst, docs/source/mocks/sublime.py, st3/sublime_lib/flags.py
The Sphinx mock module class interacts weirdly with enums, so I wrote a custom mock that provides arbitrary integers for properties that look like constants. With this done, I added a decorator that automatically adds a enum's members to its docstring.
=> Documented flags.

st3/sublime_lib/settings_dict.py, tests/test_named_settings_dict.py
Before:
```python
settings = NamedSettingsDict("Preferences.sublime-settings")
settings.name # "Preferences.sublime-settings"
```
After:
```python
settings = NamedSettingsDict("Preferences")
settings.name # "Preferences"
settings.file_name # "Preferences.sublime-settings"
```
=>  Construct NamedSettingsDict without explicit .sublime-settings extension.

st3/sublime_lib/view_utils.py, tests/test_view_utils.py
Much better than the old approach.
=> Use undocumented View.close method in `close_view`.

st3/sublime_lib/view_stream.py, tests/test_view_stream.py
Apparently the `ViewStream.print` function wasn't handling indentation correctly. I feel like it should have worked, but it didn't. Now it does.
This PR just implements `print` directly rather than using the builtin. The docstring is probably more explicit like this anyway. As a side effect, it will raise `ArgumentError` if the user passes `file` or `flush` arguments.
=> Fixed indentation for print

st3/sublime_lib/settings_dict.py
Originally, I used `{}` for the unique value of `NOT_GIVEN` (for the `pop` method). My intent was to create a new, featureless object, but I must have had JavaScript on my mind. `{}` is a `dict`, not a plain `object`. This PR uses `object()` instead. I think that this is preferable because:
- It's the simplest possible object to use.
- It stands out as being "meaningfully meaningless".
- `{} == {}` but `object() != object()`, so it's a safer convention to use in general.
There should be no functional difference in this case because `pop` correctly used `is` instead of `==`.
=> NOT_GIVEN should not be a dict.

st3/sublime_lib/__init__.py, st3/sublime_lib/window_utils.py, tests/test_window_utils.py
By analogy to `view_utils`.
`new_window` creates a new Window and returns it. This is apparently not a core feature. I'm not sure what the failure modes are. deathaxe mentioned on Discord that the Window might not be created immediately if the command is invoked from a non-main thread. If so, then we might to define another function that either a) waits for the new window or b) takes a callback.
`new_window` also takes a pile of convenience arguments (nothing complicated).
`close_window`, like `close_view`, closes a Window without showing a dialog. If there are views with unsaved changes, it will discard changes if `force` is True or raise `ValueError` otherwise.
=> Added new_window and close_window.

st3/sublime_lib/output_panel.py, st3/sublime_lib/view_stream.py, tests/test_view_stream.py
Allows you to implicitly or explicitly scroll to show the cursor.
In hindsight, I'm not sure whether the explicit `show_cursor` arguments are necessary. If the user wants to show the cursor after calling `write` or somesuch, they can call `show_cursor()`. I'll probably remove those.
=> Added show_cursor to ViewStream.

st3/sublime_lib/view_stream.py, tests/test_view_stream.py
Improved `seek()` to take any integer offset for any value of whence.
Also correctly return the new offset, even if it's different from the one that was passed in.
=> Improve `seek()`

st3/sublime_lib/__init__.py, tests/test_syntax.py, tests/test_view_utils.py
- Alphabetize submodules.
- Import public functions from `syntax` and `view_utils`.
- Modify tests to import from `sublime_lib` when possible.
The contents of `flags` and `encoding` are still not exported directly by `sublime_lib`. For `flags`, this probably makes sense. For `encoding`, we'd probably have to export the functions with different names. I am okay with punting on that for now.
=> Improve __init__.py.

st3/sublime_lib/window_utils.py, tests/test_view_stream.py, tests/test_view_utils.py
The uncovered statements are mostly utility functions that should be moved into `_utils` and tested separately.
I don't know if there's a reasonable way to test the failure in `window_utils.new_window`.
=> Improve coverage.

st3/sublime_lib/__init__.py, st3/sublime_lib/view_utils.py, tests/test_view_utils.py
Valid values are `'Unix'`, `'Windows'`, and `'CR'`. Following Sublime, we don't verify the case (Sublime will normalize the case internally).
=> Added line_endings argument to new_view, etc.

Makefile, docs/source/_static/style.css, docs/source/conf.py, docs/source/extensions/better_toctree.py, docs/source/index.rst
For #74.
Docs are now on a single page.
I totally redid the theme. The “Read the Docs” theme was very noisy. We can add more ornamentation as desired.
Notably, I removed the search function. With all the docs on one page, the browser's built-in search is good enough.
Feedback requested on organization and aesthetics.
=> Reformat docs.

.travis.yml, Makefile, docs/Makefile
Since we have the manual `index.rst`, we don't need `make source`. Should fix #86. Also fixes #85.
=> Fixed makefile for new docs.

st3/sublime_lib/resource_path.py, tests/test_resource_path.py
`from_file_path` would raise `ValueError` for installed package paths such as `$wherever/Installed Packages/My Package.sublime-syntax/foo.py`. This is probably incorrect, and it's problematic because it could cause a package relying on `from_file_path` to work as expected when cloned into `Packages` but fail when installed into `Installed Packages`.
Actual example I found while testing JS Custom:
```py
PACKAGE_NAME = ResourcePath.from_file_path(__file__).package
```
I discovered the bug when doing the final end-to-end tests before release.
This PR makes `from_file_path` check both the installed packages path and the default packages path. Code that calls `from_file_path` on Sublime-provided paths inside the package should work identically no matter how the package is installed. The …
=> from_file_path works with installed resources.

st3/sublime_lib/flags.py, tests/test_flags.py
Not all `IntFlag` enums had the necessary metaclass set. This led to an error when constructing such an enum from multiple arguments. This PR corrects the bug and adds tests to cover it.
This should probably go out as 1.2.2.
=> Added metaclass to all necessary enums.

st3/sublime_lib/flags.py, st3/sublime_lib/show_selection_panel.py, tests/test_flags.py, tests/test_selection_panel.py
Depends on #94. Before merging this, we should resolve that PR and (if appropriate) release the fix.
Previously, the `flags` argument of `show_selection_panel` was passed directly to `Window.show_quick_panel`; therefore, it had to be an int. The user could use `sublime_lib.flags.QuickPanelOption` manually.
This PR lets the user cut out the middleman and directly pass values convertible to `QuickPanelOption`, such as `"MONOSPACE_FONT"`. An iterable of values will all be passed to `QuickPanelOption`, such as `("MONOSPACE_FONT", "KEEP_OPEN_ON_FOCUS_LOST")`.
As a side effect, the argument checking is more explicit. Invalid values will raise an error as documented here rather than ambiguously in `Window.show_quick_panel`.
=> Accept selection panel flags in more formats.

docs/source/index.rst, st3/sublime_lib/__init__.py, st3/sublime_lib/_util/guard.py, st3/sublime_lib/output_panel.py, st3/sublime_lib/panel.py, st3/sublime_lib/view_stream.py, tests/test_output_panel.py, tests/test_panel.py
The existing `OutputPanel` class contains a lot of functionality that could be useful for any panel, such as the console. This PR factors out that functionality into a new `Panel` class. `OutputPanel` then extends both `ViewStream` and `Panel`. (Thankfully, this isn't a mess in Python as it would be in many other languages.)
The behavior of `OutputPanel` is unchanged, except that when you call inherited `Panel` methods on an `OutputPanel` whose view is invalid, the exception message will be slightly different. (It will still raise the same exception under the same circumstances.)
"Before" example, based on real code with irrelevant bits removed:
```python
if settings["open_console"] and self.window.active_panel() != "console":
self.window.run_command("show_panel", {"panel": "console"}) …
```
=> Added Panel class.

st3/sublime_lib/resource_path.py, tests/test_pure_resource_path.py
We have `with_suffix` copied from pathlib, but `with_suffix` is kind of annoying:
- You can't easily add a suffix without removing one.
- You can remove a suffix without adding one, but you have to pass an explicit empty string.
- It's hard to tell whether the original name had a suffix that was removed.
To solve these problems, I've created `add_suffix` and `remove_suffix`. `add_suffix` will unconditionally append its argument to the name. `remove_suffix`:
- Will raise `ValueError` if it can't do its job (unless you pass `must_remove=False`).
- Allows you to specify an optional suffix or collection of suffixes to remove, including suffixes that may differ from the `suffix` property.
Examples:
```python
path.remove_suffix('.sublime-package') # raise ValueError if the file extension is …
```
=> Added `ResourcePath.add_suffix` and `.remove_suffix`.

st3/sublime_lib/encodings.py, st3/sublime_lib/view_utils.py, tests/test_encodings.py
The docs for `from_sublime` and `to_sublime` do not specify failure behavior. Depending on the circumstances, they would either return `None` or raise `LookupError`. With this PR, the functions will raise `ValueError` if they can't do their jobs.
=> Explicit error handling for encodings.

st3/sublime_lib/show_selection_panel.py, tests/test_selection_panel.py
`show_selection_panel` will always pass a list of lists to `window.show_quick_panel` and will pad it with empty strings as necessary. If a future version of Sublime handles variable numbers of rows, we can case out the functionality.
Also modified some selection panel tests to use `with self.assertRaises()`.
=> Allow mismatched labels in show_selection_panel.

docs/source/_static/style.css, st3/sublime_lib/flags.py, tests/test_flags.py
It might also be handy to provide operator functionality for `QueryContextOperator`. Not sure of the best API for that.
EDIT: Maybe just `__call__`? E.g., `QueryContextOperator.EQUAL(1, 1)`.
=> Implemented missing flags from sublime_plugin.

st3/sublime_lib/resource_path.py
Previously, we handled the mapping between file and resource paths using `get_resource_roots()` and `get_installed_resource_roots()`. This PR consolidates the mapping logic into `ResourceRoot` objects, each representing a directory containing either zipped or unzipped packages. `file_path()` and `from_file_path()` merely iterate over the `ResourceRoot` objects and return the first result.
Other tweaks:
- Cache the list of roots instead of recomputing it each time.
- Instead of `pathlib.Path.relative_to`, use a custom implementation that doesn't spend most of its CPU time formatting an error message that we don't care about.
- Use a `wrap_path` function to avoid calling the (relatively expensive) `Path` constructor on `Path` objects.
- Avoid unnecessary reparsing when calling the …
=> Better handling of resource roots.

st3/sublime_lib/_compat/pathlib.py, st3/sublime_lib/resource_path.py, tests/test_resource_path.py
This way, if another package is using the `pathlib` dependency, then they will be using the same types. This also simplifies type checking for packages or dependencies that use sublime_lib — mypy will use the same system pathlib for everything.
We can/should do the same for enum if this makes sense.
=> Use pathlib dependency if available.

.gitignore, docs/source/extensions/prettify_special_methods.py, docs/source/mocks/sublime.py, mypy.ini, st3/sublime_lib/_compat/typing.py, st3/sublime_lib/_compat/typing_stubs.py, st3/sublime_lib/_util/collections.py, st3/sublime_lib/_util/enum.py, st3/sublime_lib/_util/glob.py, st3/sublime_lib/_util/guard.py, st3/sublime_lib/_util/named_value.py, st3/sublime_lib/_util/simple_yaml.py, st3/sublime_lib/encodings.py, st3/sublime_lib/flags.py, st3/sublime_lib/panel.py, st3/sublime_lib/resource_path.py, st3/sublime_lib/settings_dict.py, st3/sublime_lib/show_selection_panel.py, st3/sublime_lib/syntax.py, st3/sublime_lib/view_stream.py, st3/sublime_lib/view_utils.py, st3/sublime_lib/window_utils.py, tests/test_view_stream.py, unittesting.json
Includes a stub for the `typing` module. I tried vendoring the module, but it doesn't play well with 3.3, and we don't actually need it to do anything anyway.
Sphinx automatically includes type annotations in the docs. Sometimes the formatting is a mess. This should be addressed.
=> Add comprehensive type checks

st3/sublime_lib/_util/glob.py, tests/test_glob.py, tests/test_pure_resource_path.py, tests/test_resource_path.py
`ResourcePath.glob_resources()` should behave like `sublime.find_resources()`, except for the added glob functionality. Therefore, `ResourcePath.glob_resources('bar')` should not match a file named `foobar`.
=> Fixed bug in glob matching.

docs/source/conf.py, docs/source/extensions/strip_annotations.py
Hopefully fix #118.
Strip the types from the generated signatures. I suspect that the types were causing #118.
=> Strip types in documentation.

.coveragerc, st3/sublime_lib/resource_path.py, st3/sublime_lib/view_stream.py, tests/test_resource_path.py, tests/test_syntax.py
- Don't check coverage in `_compat`.
- Simplify a bit of the path translation logic by removing unused code paths.
- Fix a failing view_stream test.
=> Fix a few minor test and coverage issues.

st3/sublime_lib/flags.py
`getdoc` can return `None`, so even though we can be sure it won't, MyPy wants explicit reassurance.
MyPy is also reporting a number of errors related to the vendored enum module. Not sure how to fix that yet. See https://stackoverflow.com/questions/66282719/ignore-mypy-is-not-valid-as-a-type-error
=> Fix a MyPy issue.

st3/sublime_lib/view_utils.py, st3/sublime_lib/window_utils.py, tests/test_view_utils.py, tests/test_window_utils.py
Fix #147.
Includes #148 so the window_util tests will run.
One case is not tested. If you have an unsaved view in one window and a clone of that view in the second window, and you `close_window()` the second window, the first view should not be scratch afterward. However, it doesn't look like it's possible to set that up using the Sublime API (https://github.com/sublimehq/sublime_text/issues/3965). I tested it by hand and It Works On My Machine™.
This PR does not expose `clone_view`.
=> Revert scratchness after closing view or window

st3/sublime_lib/settings_dict.py, tests/test_settings_dict.py
Before this change, the saved value of a setting wasn't updated until after the callback was completed, so if you changed that settings object inside the callback, it would incorrectly detect that the first setting had changed again.
=> Fix a bug when changing settings in a subscribe callback.

st3/sublime_lib/settings_dict.py
For https://github.com/SublimeText/sublime_lib/pull/152#issuecomment-810678572.
My feeling is that mutating the selector result is kind of a weird thing to do and that it's probably not worth doing something complicated with mutexes.
=> Improve subscribe documentation.

st3/sublime_lib/_compat/enum.py, st3/sublime_lib/_compat/typing_stubs.py, st3/sublime_lib/_util/enum.py, st3/sublime_lib/activity_indicator.py, st3/sublime_lib/flags.py, st3/sublime_lib/view_utils.py
Fix the complaints that the current version of MyPy is lodging against the enum stuff.
Also add the missing annotation in activity_indicator.py. There should be no remaining MyPy errors.
It will be nice to delete the `_compat` stuff for the first ST4-exclusive version.
=> Fix the enum-related MyPy complaints.

st3/sublime_lib/_util/glob.py, tests/test_glob.py
For #134.
After much research and testing, I determined that the fundamental bug was that every pattern component except for `**` should match at least one character — so `/A*B/` should match `AB`, but `A/*` shouldn't match `A/`. This behavior should match other glob engines and resolve the linked bug.
This behavior varies slightly from `sublime.find_resources('*')`, which will find all resources (like `sublime.find_resources('')`.
It's probably bad news for other reasons if `sublime.find_resources()` returns directories, but at least now it shouldn't be bad news for us in particular.
=> Fix glob bug.

st3/sublime_lib/_util/weak_method.py, st3/sublime_lib/activity_indicator.py, tests/test_weak_method.py
Factor out weak_method so that it can be used elsewhere and add a basic test.
It might be useful to offer something like this as a utility function for users to pass callbacks to e.g. `sublime.set_timeout` without unnecessarily keeping things alive.
=> Factor out weak_method.

st3/sublime_lib/_util/temporary_package.py, tests/temporary_package.py, tests/test_resource_path.py
To abstract out the process of creating/cleaning up a temporary package. We'll use this for testing #136, at the very least.
=> New TemporaryPackage utility for tests.

st3/sublime_lib/_compat/enum.py
See https://github.com/sublimelsp/LSP-typescript/issues/55.
In 1.5, we use an existing `enum` module if there is one. However, the `enum` dependency is a port of `enum34`, which does not support all of the features we need. This PR always uses the vendored `enum` module, but keeps the other import in unreachable code to keep MyPy happy.
If there are no issues, we'll want to push this out as 1.5.1 ASAP.
=> Never use an existing enum module.

st3/sublime_lib/_compat/enum.py
See https://github.com/SublimeText/sublime_lib/pull/168.
=> Never use an existing enum module. (#168)

st3/sublime_lib/_compat/typing.py
=> Change typing stub to make pyright happy.
